require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WishesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Wish. As you add validations to Wish, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WishesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all wishes as @wishes" do
      wish = Wish.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:wishes)).to eq([wish])
    end
  end

  describe "GET #show" do
    it "assigns the requested wish as @wish" do
      wish = Wish.create! valid_attributes
      get :show, params: {id: wish.to_param}, session: valid_session
      expect(assigns(:wish)).to eq(wish)
    end
  end

  describe "GET #new" do
    it "assigns a new wish as @wish" do
      get :new, params: {}, session: valid_session
      expect(assigns(:wish)).to be_a_new(Wish)
    end
  end

  describe "GET #edit" do
    it "assigns the requested wish as @wish" do
      wish = Wish.create! valid_attributes
      get :edit, params: {id: wish.to_param}, session: valid_session
      expect(assigns(:wish)).to eq(wish)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Wish" do
        expect {
          post :create, params: {wish: valid_attributes}, session: valid_session
        }.to change(Wish, :count).by(1)
      end

      it "assigns a newly created wish as @wish" do
        post :create, params: {wish: valid_attributes}, session: valid_session
        expect(assigns(:wish)).to be_a(Wish)
        expect(assigns(:wish)).to be_persisted
      end

      it "redirects to the created wish" do
        post :create, params: {wish: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Wish.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved wish as @wish" do
        post :create, params: {wish: invalid_attributes}, session: valid_session
        expect(assigns(:wish)).to be_a_new(Wish)
      end

      it "re-renders the 'new' template" do
        post :create, params: {wish: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wish" do
        wish = Wish.create! valid_attributes
        put :update, params: {id: wish.to_param, wish: new_attributes}, session: valid_session
        wish.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested wish as @wish" do
        wish = Wish.create! valid_attributes
        put :update, params: {id: wish.to_param, wish: valid_attributes}, session: valid_session
        expect(assigns(:wish)).to eq(wish)
      end

      it "redirects to the wish" do
        wish = Wish.create! valid_attributes
        put :update, params: {id: wish.to_param, wish: valid_attributes}, session: valid_session
        expect(response).to redirect_to(wish)
      end
    end

    context "with invalid params" do
      it "assigns the wish as @wish" do
        wish = Wish.create! valid_attributes
        put :update, params: {id: wish.to_param, wish: invalid_attributes}, session: valid_session
        expect(assigns(:wish)).to eq(wish)
      end

      it "re-renders the 'edit' template" do
        wish = Wish.create! valid_attributes
        put :update, params: {id: wish.to_param, wish: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested wish" do
      wish = Wish.create! valid_attributes
      expect {
        delete :destroy, params: {id: wish.to_param}, session: valid_session
      }.to change(Wish, :count).by(-1)
    end

    it "redirects to the wishes list" do
      wish = Wish.create! valid_attributes
      delete :destroy, params: {id: wish.to_param}, session: valid_session
      expect(response).to redirect_to(wishes_url)
    end
  end

end
